apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gvmd-data
  namespace: gvmd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: kadalu.kadalu-pool-replica3
  resources:
    requests:
      storage: 2Gi
