apiVersion: v1
kind: Service
metadata:
  name: gvmd
  namespace: gvmd
  labels:
    app: gvmd
spec:
  type: ClusterIP
  selector:
    app: gvmd
  ports:
    - name: gmp
      port: 9390
      targetPort: 9390
