apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gvmd-app
  namespace: gvmd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: gvmd-app
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: gvmd/helm
        property: postgres_password
    - secretKey: GVM_USER
      remoteRef:
        key: gvmd/helm
        property: gvm_user
    - secretKey: GVM_PASSWORD
      remoteRef:
        key: gvmd/helm
        property: gvm_password
