apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: voidauth-config
  namespace: voidauth
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: kadalu.kadalu-pool-replica3
  resources:
    requests:
      storage: 1Gi
