apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: voidauth-app
  namespace: voidauth
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: voidauth-app
    creationPolicy: Owner
  data:
    - secretKey: storage-key
      remoteRef:
        key: voidauth/helm
        property: storage_key
    - secretKey: db-password
      remoteRef:
        key: voidauth/helm
        property: db_password
    - secretKey: db-user
      remoteRef:
        key: voidauth/helm
        property: db_user
    - secretKey: db-name
      remoteRef:
        key: voidauth/helm
        property: db_name
    - secretKey: smtp-host
      remoteRef:
        key: voidauth/helm
        property: smtp_host
        optional: true
    - secretKey: smtp-user
      remoteRef:
        key: voidauth/helm
        property: smtp_user
        optional: true
    - secretKey: smtp-pass
      remoteRef:
        key: voidauth/helm
        property: smtp_pass
        optional: true
    - secretKey: smtp-from
      remoteRef:
        key: voidauth/helm
        property: smtp_from
        optional: true
    - secretKey: smtp-port
      remoteRef:
        key: voidauth/helm
        property: smtp_port
        optional: true
    - secretKey: smtp-secure
      remoteRef:
        key: voidauth/helm
        property: smtp_secure
        optional: true
