apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: voidauth-app
  namespace: voidauth
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: voidauth-app
    creationPolicy: Owner
  data:
    - secretKey: storage-key
      remoteRef:
        key: voidauth/helm
        property: storage_key
    - secretKey: db-password
      remoteRef:
        key: voidauth/helm
        property: db_password
    - secretKey: db-user
      remoteRef:
        key: voidauth/helm
        property: db_user
    - secretKey: db-name
      remoteRef:
        key: voidauth/helm
        property: db_name
