apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: faraday-data
  namespace: faraday
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: kadalu.kadalu-pool-replica3
  resources:
    requests:
      storage: 5Gi
