apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: faraday-app
  namespace: faraday
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: faraday-app
    creationPolicy: Owner
  data:
    - secretKey: PGSQL_PASSWD
      remoteRef:
        key: faraday/helm
        property: db_password
    - secretKey: FARADAY_PASSWORD
      remoteRef:
        key: faraday/helm
        property: admin_password
