apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-helm
  namespace: postgresql
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: postgresql-helm
    creationPolicy: Owner
  data:
    - secretKey: admin-password
      remoteRef:
        key: postgresql/helm
        property: postgres_admin_password
    - secretKey: user-password
      remoteRef:
        key: postgresql/helm
        property: postgres_user_password