apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultls-app
  namespace: vaultls
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: vaultls-app
    creationPolicy: Owner
  data:
    - secretKey: api-secret
      remoteRef:
        key: vaultls/helm
        property: api_secret
    - secretKey: db-secret
      remoteRef:
        key: vaultls/helm
        property: db_secret
