apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tekton-git-auth
  namespace: tekton-pipelines
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: tekton-git-auth
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        annotations:
          tekton.dev/git-0: https://github.com
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: tekton/git
        property: username
    - secretKey: password
      remoteRef:
        key: tekton/git
        property: password
