apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-helm
  namespace: authelia
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: authelia-helm
    creationPolicy: Owner
  data:
    - secretKey: jwt-secret
      remoteRef:
        key: authelia/helm
        property: jwt_secret
    - secretKey: session.encryption.key
      remoteRef:
        key: authelia/helm
        property: session_secret
    - secretKey: storage.encryption.key
      remoteRef:
        key: authelia/helm
        property: storage_encryption_key
    - secretKey: users_database.yml
      remoteRef:
        key: authelia/users
        property: users_database.yml
