apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netalertx-data
  namespace: netalertx
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: kadalu.kadalu-pool-replica3
  resources:
    requests:
      storage: 2Gi
