apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netalertx-app
  namespace: netalertx
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: netalertx-app
    creationPolicy: Owner
  data:
    - secretKey: APP_CONF_OVERRIDE
      remoteRef:
        key: netalertx/helm
        property: app_conf_override
