apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openldap-helm
  namespace: openldap
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: openldap-helm
    creationPolicy: Owner
  data:
    - secretKey: LDAP_ADMIN_PASSWORD
      remoteRef:
        key: openldap/helm
        property: admin_password
    - secretKey: LDAP_CONFIG_ADMIN_PASSWORD
      remoteRef:
        key: openldap/helm
        property: config_admin_password