apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
    argocd.argoproj.io/tracking-id: monitoring:external-secrets.io/ExternalSecret:monitoring/grafana-secret
  name: grafana-secret
  namespace: monitoring
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: grafana/admin
        metadataPolicy: None
        property: admin_user
      secretKey: admin-user
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: grafana/admin
        metadataPolicy: None
        property: admin_password
      secretKey: admin-password
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    creationPolicy: Owner
    name: grafana-secret
    template:
      type: Opaque
