---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgB6JHVN6ncR0o9LBxnuM5/YPJfM4kPHsuPnUykbdWc70YIrIbSD/1ZRzw8LaptLErVpdf9UXwZIhuTEkcE3bBi0SRWtUQbl69DdIU/NplevjFDoOSUKAdlKOvOxB4zaEw8hX3g5gJ7q4fbnEw3Pp+tvbNgtoQTTyc2roKCqbOw7yM4vqBcrJGh4QmMFwAPJIXMWyGSv9SN9U+RquPQ7X4hq9mc5Wmi8FSGyw+6LcnZNYGASD+LqT/pB0hjtIEfWhNFSdsD+7W67Xx9PplKl2thlwfk86n2Vko76idfYl+yUHkM1MYfOXsSB5HamTVgwezYvhzqvoxRhribJJTWleKTI6oFk8PJkY0eII9p4jUg1Esgki36T0cWyZvNbZ1XHE/KsSoJaCDvCern2yAiYIuEjHfl7mgWtt0mrfjmwG3bpM7XcrWjbM5E53fMpOBa6boNMZ9Zfr8N6ezrdP/CJEgeEyQagCC+L0tRONib5JsVPbBHoRr+E5/fKGQqpkGghWz0nD0KZlk/TNN7dnfnKeCxAL5DLJIWgDPZQBEXiWdh2vf++jwPCmHzpCQNlK/CR9CiljW2N6q0dKNalr6fO0t7/0D8AGe9IYnHLWjnIw7vsaVbuQCqrk4Vd4IVeOm3KfcP+OQkXenzas4af0QMtnwHmZOa5rmzxAkfD/fOYPyxUVmVOpke9pNwdJwqQ1TaA+G5qD10f/2BZsM5aTbvRVoPtZ5+Yd9sUbjdcrm/c+Tc=
    admin-token: AgBLTt/A1HxCKIk5kB3EkgcMhm7PV3wSw3kisc0RcT5AydhkoR6bfxJB6ZVlueWqK5PzeNvuoL1IMn05gz0rsGZtvlS2hyN2EMk7K//pP0NB2yblmhecijmx+9Jg0zYB4mc4Akrv3rPN9aOE0eV3kCfcuJLtSVbp9tp5opz0TTE7TG+vdDfY6Dn4/k3NRL6+fzhflXw8xuoem7Q7PW2IyUlvM+grxj2X+ubYFZLY4OG2+Z3Y7pG/SJ+e+r7rpAw0APeh7lcFGQbYlhO+SLHC+Cs9JRkgUi25zNtBfKgr75QQ3kNTdFWFiCRCDGEQMAdI55il8wiFrLBCvqqYoeEn+n+K3HXQulL+rl7moiICmZQWGQ91LVZdVUp1bi4fB6sKT0r1TdepIb8BwkILOV0QXTQelgkQ1XYwMTFhAD068QcnsDYoafx0+N3Wf9l6JM+Wu3TQfXPEDBG2llR5L1+EcRiJgKdK+c0JCdReUtmVZWMzkOd8h92/kRPfKT+MHzHNTTjt18GvY8bsGCTDh7uAigicKQ4EbMEA1ACDLWRCXc2x8IehiiKOEff3trgFXwyHinKSEv00hjlaV4hMd3A4JT4gRe/8RouyJdLBxiGzb7MAE42Ns0YK62ay6oTMVUFim5Og7T2110MRlTgkt/EdvilfP5tMj8Ke5H1TpyMRfW8nwMOMzRhEeaQEoSEuwagUbpF2Mk6sZDknUo2bhU5UsUdI7PQwV2Q/BTxNqaggRGU=
  template:
    metadata:
      name: grafana-secret
      namespace: monitoring
    type: Opaque
