apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: influxdb-datasource
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: influxdb-datasource
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          grafana_datasource: "1"
      data:
        influxdb.yaml: |
          apiVersion: 1
          datasources:
            - name: InfluxDB
              uid: influxdb
              type: influxdb
              access: proxy
              url: http://influxdb-influxdb2.influxdb.svc.cluster.local:8086
              jsonData:
                version: Flux
                organization: influxdata
                defaultBucket: default
              secureJsonData:
                token: "{{ .token }}"
              editable: false
  data:
    - secretKey: token
      remoteRef:
        key: influxdb/grafana-readonly
        property: token
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
