apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: posta-helm
  namespace: posta
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: posta-helm
    creationPolicy: Owner
  data:
    - secretKey: jwt-secret
      remoteRef:
        key: posta/helm
        property: jwt_secret
    - secretKey: admin-email
      remoteRef:
        key: posta/helm
        property: admin_email
    - secretKey: admin-password
      remoteRef:
        key: posta/helm
        property: admin_password
    - secretKey: db-host
      remoteRef:
        key: posta/helm
        property: host
    - secretKey: db-user
      remoteRef:
        key: posta/helm
        property: user
    - secretKey: db-password
      remoteRef:
        key: posta/helm
        property: password
    - secretKey: db-name
      remoteRef:
        key: posta/helm
        property: database
    - secretKey: db-port
      remoteRef:
        key: posta/helm
        property: port
    - secretKey: db-ssl-mode
      remoteRef:
        key: posta/helm
        property: sslmode
