apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: postgresql-helm
spec:
  externalSecretName: postgresql-helm
  namespaces:
    - postgresql
  refreshTime: 1h
  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: vault-backend
    refreshInterval: 1h
    target:
      name: postgresql-helm
      creationPolicy: Owner
    data:
      - secretKey: admin-password
        remoteRef:
          key: postgresql/helm
          property: postgres_admin_password
      - secretKey: user-password
        remoteRef:
          key: postgresql/helm
          property: postgres_user_password
