apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: postgresql-helm
spec:
  refreshInterval: 1h
  externalSecretName: postgresql-helm
  namespaceSelector:
    matchNames:
      - postgresql
  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: vault-backend
    target:
      name: postgresql-helm
      creationPolicy: Owner
    data:
      - secretKey: admin-password
        remoteRef:
          key: postgresql/helm
          property: postgres_admin_password
      - secretKey: user-password
        remoteRef:
          key: postgresql/helm
          property: postgres_user_password