apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-app
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: authentik-app
    creationPolicy: Owner
  data:
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: authentik/helm
        property: secret_key
    - secretKey: AUTHENTIK_POSTGRESQL__PASSWORD
      remoteRef:
        key: authentik/helm
        property: db_password
