apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-media
  namespace: authentik
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: kadalu.kadalu-pool-replica3
  resources:
    requests:
      storage: 2Gi
