apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-helm
  namespace: authentik
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: authentik-helm
    creationPolicy: Owner
  data:
    - secretKey: secret_key
      remoteRef:
        key: authentik/helm
        property: secret_key
    - secretKey: password
      remoteRef:
        key: authentik/helm
        property: postgres_password

