apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certctl
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/iamenr0s/gitops-argocd.git
    targetRevision: main
    path: certctl
  destination:
    server: https://kubernetes.default.svc
    namespace: certctl
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: certctl-server
      namespace: certctl
      jsonPointers:
        - /data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
