apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: certctl
  namespace: certctl
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/service.serversscheme: https
    traefik.ingress.kubernetes.io/service.serverstransport: certctl-certctl-transport@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - certctl.apps.k8s.enros.me
      secretName: certctl-tls
  rules:
    - host: certctl.apps.k8s.enros.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: certctl-server
                port:
                  number: 8443
