apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: certctl
resources:
  - namespace.yml
  - serviceaccount.yml
  - rbac.yml
  - configmaps.yml
  - deployment.yml
  - daemonset.yml
  - service.yml
  - ingress.yml
  - middleware.yml
  - tls-server.yml
  - vault-credentials.externalsecret.yml
