apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: certctl
  labels:
    app.kubernetes.io/name: certctl
    app.kubernetes.io/instance: certctl
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: certctl
  labels:
    app.kubernetes.io/name: certctl
    app.kubernetes.io/instance: certctl
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: certctl
subjects:
  - kind: ServiceAccount
    name: certctl
    namespace: certctl
