apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: certctl-selfsigned-issuer
  namespace: certctl
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certctl-server-tls
  namespace: certctl
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  secretName: certctl-server-tls
  usages:
    - server auth
  dnsNames:
    - certctl-server
    - certctl-server.certctl.svc
    - certctl-server.certctl.svc.cluster.local
    - localhost
  issuerRef:
    name: certctl-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
