apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: certctl-server-credentials
  namespace: certctl
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: certctl-server
    creationPolicy: Orphan
    template:
      type: Opaque
      data:
        database-url: "postgres://certctl:{{ .db_password }}@postgresql.postgresql.svc.cluster.local:5432/certctl?sslmode=disable"
        api-key: "{{ .api_key }}"
  data:
    - secretKey: db_password
      remoteRef:
        key: certctl/config
        property: db_password
    - secretKey: api_key
      remoteRef:
        key: certctl/config
        property: api_key
