apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karpor-ai
  namespace: karpor
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: karpor-ai
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: AI_AUTH_TOKEN
      remoteRef:
        key: karpor/helm
        property: ai_auth_token
    - secretKey: AI_BASE_URL
      remoteRef:
        key: karpor/helm
        property: ai_base_url