namespace: karpor
namespaceEnabled: true
registryProxy: ""
global:
  image:
    imagePullPolicy: IfNotPresent
server:
  name: karpor-server
  replicas: 1
  port: 7443
  image:
    repo: kusionstack/karpor
    tag: ""
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
      ephemeral-storage: 2Gi
    limits:
      cpu: 500m
      memory: 1Gi
      ephemeral-storage: 10Gi
  enableRbac: false
  serviceType: ClusterIP
  ai:
    authToken: ""
    baseUrl: "https://api.openai.com/v1"
    backend: "openai"
    model: "gpt-3.5-turbo"
    temperature: 1.0
    topP: 1.0
    proxy:
      enabled: false
      httpProxy: ""
      httpsProxy: ""
      noProxy: ""
syncer:
  name: karpor-syncer
  replicas: 1
  port: 7443
  image:
    repo: kusionstack/karpor
    tag: ""
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
      ephemeral-storage: 2Gi
    limits:
      cpu: 500m
      memory: 1Gi
      ephemeral-storage: 10Gi
elasticsearch:
  name: elasticsearch
  replicas: 1
  port: 9200
  image:
    repo: docker.elastic.co/elasticsearch/elasticsearch
    tag: "8.6.2"
  resources:
    requests:
      cpu: "2"
      memory: 4Gi
      ephemeral-storage: 10Gi
    limits:
      cpu: "2"
      memory: 4Gi
      ephemeral-storage: 10Gi
etcd:
  name: etcd
  replicas: 1
  port: 2379
  image:
    repo: quay.io/coreos/etcd
    tag: "v3.5.11"
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
      ephemeral-storage: 2Gi
    limits:
      cpu: 500m
      memory: 1Gi
      ephemeral-storage: 10Gi
  persistence:
    # enabled: true
    size: 10Gi
    accessModes:
      - ReadWriteOnce
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: "-"
job:
  image:
    repo: kusionstack/karpor
    tag: ""
