apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-ui
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: https://locustbaby.github.io/trivy-ui/
      chart: trivy-ui
      targetRevision: 0.0.3
      helm:
        valueFiles:
          - $values/trivy-ui/values.yml
    - repoURL: https://github.com/iamenr0s/gitops-argocd.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/iamenr0s/gitops-argocd.git
      path: trivy-ui
      targetRevision: main
      kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: trivy-ui
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
