apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trivy-ui-kubeconfigs
  namespace: trivy-ui
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: kubeconfigs
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: local
      remoteRef:
        key: trivy-ui/kubeconfigs
        property: local
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
