apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-admin-password
  namespace: harbor
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: admin-password
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: HARBOR_ADMIN_PASSWORD
      remoteRef:
        key: harbor/admin
        property: admin_password
