apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-hub
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: oci://ghcr.io/traefik/helm
      chart: traefik-hub
      targetRevision: 4.2.0
      helm:
        valueFiles:
          - $values/traefik-hub/values.yml
    - repoURL: https://github.com/iamenr0s/gitops-argocd.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/iamenr0s/gitops-argocd.git
      path: traefik-hub
      targetRevision: main
      kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik-hub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
