apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hub-agent-token
  namespace: traefik-hub
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: hub-agent-token
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: token
      remoteRef:
        key: traefik-hub/token
        property: token
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
