apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: domain-monitor-mariadb-creds
  namespace: mariadb
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: domain-monitor-mariadb-creds
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: db-password
      remoteRef:
        key: domain-monitor/helm
        property: db_password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: domain-monitor
  namespace: mariadb
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  mariaDbRef:
    name: mariadb
  characterSet: utf8mb4
  collate: utf8mb4_unicode_ci
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: domain-monitor
  namespace: mariadb
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  mariaDbRef:
    name: mariadb
  passwordSecretKeyRef:
    name: domain-monitor-mariadb-creds
    key: db-password
  maxUserConnections: 20
  host: "%"
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: domain-monitor
  namespace: mariadb
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    - "ALL PRIVILEGES"
  database: "domain-monitor"
  table: "*"
  username: domain-monitor
  grantOption: false
  host: "%"
