apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
  namespace: mariadb
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  rootPasswordSecretKeyRef:
    name: mariadb-secrets
    key: root-password
    generate: false

  username: app
  passwordSecretKeyRef:
    name: mariadb-secrets
    key: password
    generate: false
  database: app

  image: mariadb:11.8.5
  imagePullPolicy: IfNotPresent

  port: 3306

  storage:
    size: 10Gi
    storageClassName: kadalu.kadalu-pool-replica3
    volumeClaimTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: kadalu.kadalu-pool-replica3

  service:
    type: ClusterIP

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  livenessProbe:
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

  readinessProbe:
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

