apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mariadb-secrets
  namespace: mariadb
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: mariadb-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: root-password
      remoteRef:
        key: mariadb/credentials
        property: root_password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        key: mariadb/credentials
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
