nameOverride: ""
fullnameOverride: ""
crds:
  enabled: false
image:
  repository: docker-registry3.mariadb.com/mariadb-operator/mariadb-operator
  pullPolicy: IfNotPresent
  tag: ""
imagePullSecrets: []
logLevel: INFO
clusterName: cluster.local
currentNamespaceOnly: false
ha:
  enabled: false
  replicas: 3
metrics:
  enabled: false
  serviceMonitor:
    enabled: true
    additionalLabels: {}
    interval: 30s
    scrapeTimeout: 25s
    metricRelabelings: []
    relabelings: []
serviceAccount:
  enabled: true
  automount: true
  annotations: {}
  extraLabels: {}
  name: ""
rbac:
  enabled: true
  aggregation:
    enabled: true
extraArgs: []
extraEnv: []
extraEnvFrom: []
extraVolumes: []
extraVolumeMounts: []
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
resources: {}
nodeSelector: {}
tolerations: []
topologySpreadConstraints: []
priorityClassName: ""
affinity: {}
pdb:
  enabled: false
  maxUnavailable: 1
pprof:
  enabled: false
  port: 6060
webhook:
  enabled: true
  image:
    repository: docker-registry3.mariadb.com/mariadb-operator/mariadb-operator
    pullPolicy: IfNotPresent
    tag: ""
  imagePullSecrets: []
  ha:
    enabled: false
    replicas: 3
  cert:
    certManager:
      enabled: false
      issuerRef: {}
      duration: ""
      renewBefore: ""
      revisionHistoryLimit: 3
    secretAnnotations: {}
    secretLabels: {}
    ca:
      path: ""
      key: ""
    path: /tmp/k8s-webhook-server/serving-certs
  port: 9443
  hostNetwork: false
  serviceMonitor:
    enabled: true
    additionalLabels: {}
    interval: 30s
    scrapeTimeout: 25s
    metricRelabelings: []
    relabelings: []
  serviceAccount:
    enabled: true
    automount: true
    annotations: {}
    extraLabels: {}
    name: ""
  annotations: {}
  extraArgs: []
  extraVolumes: []
  extraVolumeMounts: []
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  topologySpreadConstraints: []
  priorityClassName: ""
  affinity: {}
  pdb:
    enabled: false
    maxUnavailable: 1
certController:
  enabled: true
  image:
    repository: docker-registry3.mariadb.com/mariadb-operator/mariadb-operator
    pullPolicy: IfNotPresent
    tag: ""
  imagePullSecrets: []
  ha:
    enabled: false
    replicas: 3
  caLifetime: 26280h
  certLifetime: 2160h
  renewBeforePercentage: 33
  requeueDuration: 5m
  serviceMonitor:
    enabled: true
    additionalLabels: {}
    interval: 30s
    scrapeTimeout: 25s
    metricRelabelings: []
    relabelings: []
  serviceAccount:
    enabled: true
    automount: true
    annotations: {}
    extraLabels: {}
    name: ""
  extraArgs: []
  extraVolumes: []
  extraVolumeMounts: []
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  topologySpreadConstraints: []
  priorityClassName: ""
  affinity: {}
  pdb:
    enabled: false
    maxUnavailable: 1
config:
  galeraLibPath: /usr/lib/galera/libgalera_smm.so
  mariadbDefaultVersion: "11.8"
  mariadbImage:
    repository: docker-registry1.mariadb.com/library/mariadb
    tag: 11.8.5
  mariadbImageName: docker-registry1.mariadb.com/library/mariadb
  maxscaleImage:
    repository: docker-registry2.mariadb.com/mariadb/maxscale
    tag: 23.08.5
  exporterImage:
    repository: prom/mysqld-exporter
    tag: v0.15.1
  exporterMaxscaleImage:
    repository: docker-registry2.mariadb.com/mariadb/maxscale-prometheus-exporter-ubi
    tag: v0.0.1