apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kadalu
resources:
- https://raw.githubusercontent.com/kadalu/kadalu/refs/heads/devel/manifests/kadalu-operator.yaml
#- https://github.com/kadalu/kadalu/releases/download/1.3.0/csi-nodeplugin.yaml
