apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lastsignal
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/iamenr0s/gitops-argocd.git
    targetRevision: main
    path: lastsignal
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: lastsignal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true