apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lastsignal-helm
  namespace: lastsignal
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: lastsignal-helm
    creationPolicy: Owner
  data:
    - secretKey: rails-master-key
      remoteRef:
        key: lastsignal/helm
        property: rails_master_key
    - secretKey: smtp-address
      remoteRef:
        key: lastsignal/helm
        property: smtp_address
    - secretKey: smtp-port
      remoteRef:
        key: lastsignal/helm
        property: smtp_port
    - secretKey: smtp-username
      remoteRef:
        key: lastsignal/helm
        property: smtp_username
    - secretKey: smtp-password
      remoteRef:
        key: lastsignal/helm
        property: smtp_password
    - secretKey: smtp-from
      remoteRef:
        key: lastsignal/helm
        property: smtp_from
    - secretKey: database-url
      remoteRef:
        key: lastsignal/helm
        property: database_url