apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: telegraf-operator-classes
  namespace: telegraf
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: telegraf-operator-classes
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        infra: |
          [[outputs.influxdb_v2]]
            urls = ["http://influxdb.influxdb:8086"]
            token = "{{ .token }}"
            organization = "influxdata"
            bucket = "default"
          [global_tags]
            env = "ci"
            hostname = "$HOSTNAME"
            nodename = "$NODENAME"
            type = "infra"
        x509-cert-check: |
          [[inputs.x509_cert]]
            sources = [{{ .cert_urls }}]
            timeout = "5s"
          [[outputs.influxdb_v2]]
            urls = ["http://influxdb.influxdb:8086"]
            token = "{{ .token }}"
            organization = "influxdata"
            bucket = "default"
          [global_tags]
            env = "ci"
            hostname = "$HOSTNAME"
            nodename = "$NODENAME"
            type = "x509-cert-check"
  data:
    - secretKey: token
      remoteRef:
        key: influxdb/admin
        property: admin_token
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: cert_urls
      remoteRef:
        key: telegraf/x509-cert
        property: urls
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
