apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: telegraf-x509-cert-urls
  namespace: telegraf
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: telegraf-x509-cert-urls
    creationPolicy: Owner
  data:
    - secretKey: urls
      remoteRef:
        key: telegraf/x509-cert
        property: urls
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
