apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: influxdb-auth
  namespace: influxdb
spec:
  encryptedData:
    admin-password: AgDOJYLOy37Vw/3r5T5jCfYngNeR8Gkoa66FBnmZI/d46e9PVWqdW3UZGZKnMgPmKezGek76NkHP4RWuNLzeXbspDcAvmEjkKRUMUnIu7Ie12PUi2TamCo2ZmCtzR4QtoE1f1FDJAjbQi1pb+m14g0pIJr8w1DX23RMFp2chQPVAn+5QIh5QPq9aDe4OJuQADUUrS8yaHBOzLCL9kALQosRZ68VmY0vAyblyRNGEyz9PT7VvAmkzz359BLx9INKuJMezG+aaCzzCQvCJ9waRsoaklRcCqu9+9s8AGsz4Sk3UNWBf86oa0BlI5gV6haL9ry7w93cl1ykQ6WmwA3rZ1Dwygjb5EUkqxOuMYX/IPwV+DLjxrTj5YO6d83HSlIKT1tr4kIyJsEPa1Irz/+Bcwn1+grSVSuWgmhK/T1qrFLTSaJHZ6oprTBR6xmGnpTaQw8f7el9O5RL+enKQ+shtFEescd02DXxc9GvF0OxakNC5Vn1a/OjVyKf3js2HFgz9qV0am8dz+By5qUZPF1KN/o/nagyPGfI+Duu12ry5GqQgYUEkVXd3h7PTATO4aHL4KlSCOL6j+H2Csn9k8DOPJnfoSNHYtaxChU23t/DMcc/pcwrC+1ILA2h/ybrWo+0rLSQO/tj1+w8IagsfyTKLeOr0+J8jEViqZkjUe4cYSVslW4TgXzUI6yusGcmYEymvr4uywGTZS5blli8OZC1KwKSlxM9KmI06FTeUQCOZES0DVw==
    admin-token: AgAn9CnvnC2W3oKfWgOF5Gq1Bxf4ppl30AJyjM9MF2H2VJ7vPqefrPaqJazGK9bA92bsw8+1J78RUoiTSyOjUBxWSPhBpKxlZNEwbCN4Bl/jb7Q1XkkNJSpwCeV+p1mk3buWo4T+l3/r9Cn/y33Tc0QsBHDphLs0pou7sAfURdExeDzn7UEBdhru+KXq4xCQzIx0xx6IWLPn4d5ErEtMHiBTzO0YycAEWo8GsV3TpbhtJcXq3J2ZhGOvBzuhfDPoTgALz2kf0uOyIOjrYIBSNmegsPIIiXlqjudR1w35Xa5Wdc7/E65lwY6ssJQSwbZG46Ni9lc+ZKG8k/uvxEXoER/mCROzrB0aRD5KwqJGc+EtVELkNdV2YHmieWukAYDt4+wauy5USYnJCgVU+5WwzFguS+Xvc0xkGGbZHM87VsgyG2lL4ZasoaGkPp/rPmX6spABECs+4+WZtfdLhvPSRnevRp9ORZs6Hj+c+TwYnzrjIAu3zOQ1KG13xwy4T016lYdVaFCWt7+cd8QnIpUFwFlZ6XANe6KPWq7foHXtIKS62pH5R6bsvSTRTna5ftiOdRyP+l3L7vWcylIT0wc+3ahcRtE6BuZ1b59zOhjc87LveJv2gx9SV246jH8XEwA8f4bbtClJIiJ0OZNL1Wb+Q5jePkD8vHswqre8Eed2dK760EWU5bCUt35gAYlKLBLjvh9FtngltB0C2hwaYT2v5HbJl14Vb8yP0ShNNjpjhlRiPg==
  template:
    metadata:
      name: influxdb-auth
      namespace: influxdb
    type: Opaque
