apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: influxdb-influxdb2-auth
  namespace: influxdb
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: influxdb-influxdb2-auth
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: admin-password
      remoteRef:
        key: influxdb/admin
        property: admin_password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: admin-token
      remoteRef:
        key: influxdb/admin
        property: admin_token
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
