---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: influxdb-influxdb2-auth
  namespace: influxdb
spec:
  encryptedData:
    admin-password: AgB9sd4SzS5Kh7Nx1kAdRtpGpLrxq5FLeuKdlnFvbTAFJnT97I+lsPZEuXewT1iPk9OrMu1L0RjoN4+I2yEdw/sR80oYq43qymHVmVH/dk4yWLUmMzbx7fZ1GgPSG4nGbp3t2BcKjYCl+nyaZ5ck2vsI4kZEt7b+8Qrih7dBIi36l5KRH5flb1UCe/wvftCFxrZl1nOrW8GdH26EQEJAf5WAFOiLnlO1RuqjGJbsuK6eH+e25SiPvY070OXE/O/iv5h7PkYlDpnh0XzOzzUBpYHNWhSollKBwLrAD4FjtXeNjcVqUn2nrbodkmBaj7cAeWvWuVP+XbfV5+0GHsVFxK/A36L+lze3lnWzcIVj7vloCnqqFoZVpuidJJk+SNVhLzgeC8GJfJNhZHcfvspFNdiV0INKpIrJdlYMW7G8ujIvsOJ8TBmns5YAvVLbuRaZKyqbzeKg0f8IRTVUlMrvq/oPtWtNjefD2i8Nj+98DSWQOP0fIxUvlb15ib+h781hHv3cb8QA+br2YGCBz6aSdxyVjpa75y0CQAbwg+pCHR4UsvKXaERbzvhpq3Ph0XTzv2WUwZhqjgXwG/V7i4qFbETNZvlog4YGls1bbrFA+npKsWzMDWJUKLYL2w0y9oykXcBEynGAh5pQXKSudaOxaUiSNk4x2YVJ4GOTctxF/8b1wdzCr1jghlPArkq9UKrJf5NFNktwdRmvaWJtbudQ6+8mfmZE1AqXbXj0SF8Ys2eepQ==
    admin-token: AgCpihg6fiq6CMJHhiWgoji6UGVE7FSOsVDrAnPyvh2TxH0YPj8J4nAlK8tc4YaeuGXd+OtFZ/ScbHEcX6Ccm7HnqRcV5h3+IhkL5pKpSMwAtlJQOwH25mnySHJ2fAjR5Mmg9c0MwI9iBjEnxSQ2hhycmUEd0d4ZT+/45VGdvdh6fmSzZomYjmMzCb/E0eydFysVkPSrFd3ST3QHOOXRpINKxNTFSjxGPiuUQl4zCF04Yq8BlMDt1yXKb/MI27FzDki64mMpLGCmjtZeOIoyX3z4d9rgDPMNLcJLoIrzGJ9O2zn6/Y8/nf5719ei82mIaGYDheLyDr6Fr/Z8lZy2ycOU0FXi40hIBcsqgkSU9EE1JF4qeKJlOdeJJsBWHFRFpq0LVGy9KY6slxBKyn3xfp4zvw/xUzoKGeKoJjqdZCwLVXvZ0IcAOVdQZ5RRLPEp1laIdhiLpAdrypgAaGAdYbqlENhODyQJuDix4EO0nzxuooMoMYwFwda8jcpZRqBQRpfL+yZlNPRnEiqXUnB0wxIuJXi9X2Aq1dn6QktaaVSgJHxo2NV1OsOuYIF6hOINbe3gUkBKBJvi9BA7PPmdE0nDdf4sSNI1QpENfioyKs2kf+lcNQxiq/m83ScK83GNU8X+Zaom2xi8NdJAJehuado3Etv+fFrc+G8Kaz6xA9fq2ONpcqQspyepFh/aZBsraoUCulOXhiJCgy1TmTJosGDSjdwIG/ebTnPYxkWWAE5wFQ==
  template:
    metadata:
      name: influxdb-influxdb2-auth
      namespace: influxdb
    type: Opaque
