apiVersion: v1
data:
  admin-password: TjF4TUhmYXBkY0JkNk5FcFdXRDBIblphR1VBdThISWk=
  admin-token: UWRtZnJrdVJhSmcxc1B1bFJ6ektuQUNyY1ZxVXJHOXg=
kind: Secret
metadata:
  name: influxdb-influxdb2-auth
  namespace: influxdb
