apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openvas-vt-data
  namespace: openvas-scanner
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: kadalu.kadalu-pool-replica3
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openvas-notus-data
  namespace: openvas-scanner
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: kadalu.kadalu-pool-replica3
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openvas-gpg-data
  namespace: openvas-scanner
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: kadalu.kadalu-pool-replica3
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openvas-config
  namespace: openvas-scanner
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: kadalu.kadalu-pool-replica3
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openvas-log
  namespace: openvas-scanner
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: kadalu.kadalu-pool-replica3
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openvasd-storage
  namespace: openvas-scanner
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: kadalu.kadalu-pool-replica3
  resources:
    requests:
      storage: 2Gi
