apiVersion: v1
kind: Service
metadata:
  name: openvasd
  namespace: openvas-scanner
  labels:
    app: openvasd
spec:
  type: ClusterIP
  selector:
    app: openvasd
  ports:
    - name: http
      port: 3000
      targetPort: 3000
