apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openvas-scanner-app
  namespace: openvas-scanner
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: openvas-scanner-app
    creationPolicy: Owner
  data:
    - secretKey: STORAGE_KEY
      remoteRef:
        key: openvas-scanner/helm
        property: storage_key
