---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: acme-contact
  namespace: cert-manager
spec:
  encryptedData:
    email: AgAaZF9MqvzAiCQ03rtgnuHOK+/47QsAcUGUEZd1q9gBIpcvROphgvSeaVOvZtuUNy8j0Zc2iIOENptTnVPzzxzS0czDGFfcQLFtzN5vR6Zh+F5Dsdd9TdTrFfKbWcqyEJaDNC+hU029OpabY28f/t5d3SH8MWSyx+lMoTuxPqiRZ/2ocfjUn7lrq6XJTCnU52mu1Lr1vYTbnR5FcYFQsokRkyygkntCf2KwYRTlXut2Jo4XmuJbeooXLlYZfRpnms1aQkhSLXcqY5wNT/3JCGCqyi3AwZTjchWlUQSNzlbywMxRJa0h/lBevVvekOw0BhXCwg9t2Wdma+ZZ5Qx2zb+BjZ5o7kAI1GiWh4cQgACC9JdeD5mGRUn+9GjQfTu4G5mOPSD2RezNCr/ObFfifLbj9MHnWRUiNe9bTefXpz4m8fGHk8eBmztX+320lUKHGiAaDGH2vHlijrevr7XHKH8SXif3gmttT5rGxsB98FbZ38/K/FyLJdhQt1uR8m3YnN/A4PyC7xWdyzBOpmOKf50629RUrhd/SZdbdOmIG7lzC2homDGf1pL5gzZFE/cvtOzjfVdanylmWzVjSfUxYbb+3SgdEF94ll4cUW6NzJgjUzdb4DgDDZHtSTfzWHGKBD+BRPhBnAyX7pnXkTANQBl4U28y8EdhOmAXieiB2hFKDbXJ7T8Z5tC1eUjvLAgtdYwdsSD3sccHH9Eum5eX
  template:
    metadata:
      name: acme-contact
      namespace: cert-manager
