apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: acme-contact
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: acme-contact
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: email
      remoteRef:
        key: cert-manager/acme
        property: email
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
