apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowdsec-enroll
  namespace: crowdsec
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: crowdsec-enroll
    creationPolicy: Owner
  data:
    - secretKey: ENROLL_KEY
      remoteRef:
        key: crowdsec/helm
        property: enroll_key
