apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowdsec-db
  namespace: crowdsec
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: crowdsec-db
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: crowdsec/helm
        property: db_password
